services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: assembleia
      POSTGRES_USER: devlocal
      POSTGRES_PASSWORD: apivotacao

      PGDATA: /var/lib/postgresql/data
    volumes:
      - db-assembliea-data:/var/lib/postgresql/data
    ports:
        - "5432:5432"
    networks:
        - api-network

  fakeapi:
    image: emanuelbc/fake-cpf-api:1.0
    ports:
      - "8081:8081"

networks:
  api-network:
    driver: bridge

volumes:
  db-assembliea-data: